input_attributes = [
    "age",
    "gender",
    "bmi",
    "metabolic rate",
    "physical activity intensity",
    "blood pressure",
    "diabetic",
    "heart disease",
    "anemia",
    "lactose intolerance",
    "nutrition goal"
]

output_attributes = [
    "proteins",
    "carbohydrates",
    "fats",
    "calcium",
    "vitamin_a",
    "vitamin_c",
    "calories"
]

[range.bmi]
min = 15
max = 45
divisions = 6

[range.age]
min = 14
max = 70
divisions = 7

[range.proteins]
min = 50
max = 300
divisions = 5

[range.carbohydrates]
min = 150
max = 350
divisions = 5

[range.fats]
min = 20
max = 120
divisions = 5

[range.calcium]
min = 1100
max = 1300
divisions = 5

[range.vitamin_a]
min = 1100
max = 1300
divisions = 5

[range.vitamin_c]
min = 700
max = 900
divisions = 5

[range.calories]
min = 1500
max = 4000
divisions = 5