input_attributes = [
    "age",
    "gender",
    "bmi",
    "metabolic rate",
    "physical activity intensity",
    "blood pressure",
    "diabetic",
    "heart disease",
    "anemia",
    "lactose intolerance",
    "nutrition goal"
]

output_attributes = [
    "proteins",
    "carbohydrates",
    "fats",
    "calcium",
    "vitamin_a",
    "vitamin_c",
    "calories"
]

[range.height]
min = 1.2
max = 2.1

[range.weight]
min = 20
max = 200

[range.bmi]
min = 15
max = 45
divisions = 6

[range.age]
min = 14
max = 70
divisions = 7

[range.proteins]
min = 50
max = 300
divisions = 5

[range.carbohydrates]
min = 150
max = 350
divisions = 5

[range.fats]
min = 20
max = 120
divisions = 5

[range.calcium]
min = 1100
max = 1300
divisions = 5

[range.vitamin_a]
min = 1100
max = 1300
divisions = 5

[range.vitamin_c]
min = 700
max = 900
divisions = 5

[range.calories]
min = 1500
max = 4000
divisions = 5

[values]
gender = ["Female", "Male"]
metabolic_rate = ["Very low", "Low", "Mid", "High", "Very high"]
physical_activity_intensity = ["Very low", "Low", "Mid", "High", "Very high"]
blood_pressure = ["Hypotension", "Normal", "Hypertension"]
diabetic = ["Normal", "High", "Severely high"]
heart_disease = ["Yes", "No"]
lactose_intolerance = ["Normal", "High", "Severely high"]
nutrition_goal = ["Gain weight", "Lose weight", "Maintain weight", "Gain muscle", "Gain endurance"]